name = "ghost"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "radar-db"
database_id = "b3d3f114-24fc-4869-a84a-0deb0f7675a0"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "radar-copwatch"

[[routes]]
pattern = "ghost.theradicalparty.com/*"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "radar.theradicalparty.com/*"
zone_name = "theradicalparty.com"

[triggers]
crons = ["*/5 * * * *"]
